import { Applicant, ParsedFileSheet } from '../types/applicant';
import {
  buildNormalizedApplicant,
  RawApplicantInput,
  recomputeApplicantsMetadata,
} from './duplicateDetector';
import { autoRecommendColumnMapping } from './normalizers';

const SAMPLE_RAW_APPLICANTS: RawApplicantInput[] = [
  {
    id: 'sample_01',
    name: '  김민준 ',
    phone: '+82 10-3948-1920',
    examNumber: 'ADM-2026-0101',
    email: 'MinJun.Kim@gmail.com ',
    address: '서울특별시 서초구 반포대로 58',
    recruitmentCategory: '일반행정 (전국)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급 (심화)',
    writtenScore: 92.5,
    interviewScore: 94.0,
    finalResult: '최종 합격',
    tags: ['우수성적', '한국사1급'],
    memo: '필기 및 면접 점수 최상위권. 직무 적합성 우수.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_02',
    name: '김민준',
    phone: '01039481920',
    examNumber: 'TECH-2026-0042',
    email: 'minjun.kim@gmail.com',
    address: '서울특별시 서초구 반포대로 58',
    recruitmentCategory: '전산/데이터 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급 (심화)',
    writtenScore: 88.0,
    interviewScore: 89.5,
    finalResult: '예비 합격',
    tags: ['복수응시', '전산자격보유'],
    memo: '일반행정과 전산 직렬에 복수 응시한 수험생. 예비 순번 1번.',
    sourceFileName: '전산직렬_추가접수분.csv',
  },
  {
    id: 'sample_03',
    name: '이서연',
    phone: '010-8271-4409',
    examNumber: 'ADM-2026-0108',
    email: 'seoyeon.lee@kakao.com',
    address: '경기도 성남시 분당구 판교역로 166',
    recruitmentCategory: '일반행정 (지역: 경기)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급 (기본)',
    writtenScore: 89.5,
    interviewScore: 92.0,
    finalResult: '최종 합격',
    tags: ['경기지역', '면접우수'],
    memo: '지역 인재 추천 요건 충족. 최종 합격 등록 안내 발송 완료.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_04',
    name: '이 서 연',
    phone: '1082714409',
    examNumber: 'ADM-2026-0108',
    email: 'seoyeon.lee@kakao.com',
    address: '경기도 성남시 분당구',
    recruitmentCategory: '일반행정 (지역: 경기)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급',
    writtenScore: 89.5,
    interviewScore: null,
    finalResult: '심사 중',
    tags: ['중복접수'],
    memo: '동일 수험번호로 온라인 재접수된 건 (주소 보완 내역).',
    sourceFileName: '온라인접수_2차배포.xlsx',
  },
  {
    id: 'sample_05',
    name: '박지훈',
    phone: '010-384-991', // 연락처 형식 오류
    examNumber: 'TECH-2026-0088',
    email: 'jihun.park94@naver.com',
    address: '인천광역시 부평구 부평대로 24',
    recruitmentCategory: '전산/데이터 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '대상 (경증)',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 86.0,
    interviewScore: 85.0,
    finalResult: '심사 중',
    tags: ['장애구분', '연락처확인필요'],
    memo: '연락처 끝자리 자릿수 오류로 유선 연락 불가. 이메일로 긴급 확인 요청.',
    sourceFileName: '전산직렬_추가접수분.csv',
  },
  {
    id: 'sample_06',
    name: '최수아',
    phone: '010-5502-7731',
    examNumber: 'WEL-2026-0015',
    email: 'sua.choi@@gmail.com', // 이메일 형식 오류
    address: '대전광역시 유성구 대학로 99',
    recruitmentCategory: '사회복지 (일반)',
    supportNeeds: '확대문제지',
    disabilityStatus: '비대상',
    lowIncomeStatus: '기초생활수급자',
    historyScore: '3급',
    writtenScore: 84.5,
    interviewScore: 88.0,
    finalResult: '최종 합격',
    tags: ['저소득대상', '편의지원'],
    memo: '저소득 전형 가점 5% 반영 완료. 이메일 @ 오타 보정 필요.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_07',
    name: '정현우',
    phone: '010-9012-6634',
    examNumber: 'ENG-2026-0012',
    email: 'hyunwoo.jung@devmail.kr',
    address: '대구광역시 수성구 달구벌대로 2450',
    recruitmentCategory: '토목/시설 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 94.0,
    interviewScore: 91.5,
    finalResult: '최종 합격',
    tags: ['수석후보', '자격가점'],
    memo: '기사 자격 가점 및 한국사 1급 충족. 기술직 전체 수석.',
    sourceFileName: '기술직_접수명단.xlsx',
  },
  {
    id: 'sample_08',
    name: '강하은',
    phone: '010-2219', // 연락처 오류
    examNumber: 'PR-2026-0051',
    email: 'haeun.kang@naver', // 이메일 오류
    address: '부산광역시 해운대구 마린시티2로 33',
    recruitmentCategory: '홍보/기획 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '해당없음',
    writtenScore: 78.0,
    interviewScore: 75.0,
    finalResult: '불합격',
    tags: ['서류확인필요'],
    memo: '연락처 및 이메일 서식 미비로 추가 증빙 필요.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_09',
    name: '조성민',
    phone: '010-7123-8840',
    examNumber: 'TECH-2026-0099',
    email: 'sungmin.cho@company.io',
    address: '서울특별시 마포구 월드컵북로 400',
    recruitmentCategory: '전산/데이터 (일반)',
    supportNeeds: '별도시험실',
    disabilityStatus: '대상 (중증)',
    lowIncomeStatus: '차상위계층',
    historyScore: '2급',
    writtenScore: 90.0,
    interviewScore: 93.0,
    finalResult: '최종 합격',
    tags: ['장애인전형', '별도시험실배정'],
    memo: '중증장애인 편의제공(별도시험실, 1.5배 시간연장) 지원 완료.',
    sourceFileName: '전산직렬_추가접수분.csv',
  },
  {
    id: 'sample_10',
    name: '윤지아',
    phone: '010-6341-0982',
    examNumber: 'ADM-2026-0211',
    email: 'jia.yoon@studio.kr',
    address: '세종특별자치시 한누리대로 411',
    recruitmentCategory: '일반행정 (전국)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 87.5,
    interviewScore: 88.0,
    finalResult: '예비 합격',
    tags: ['예비2번'],
    memo: '합격선 근접자. 결원 발생 시 2순위 예비합격자 안내 대상.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_11',
    name: '장도윤',
    phone: '010-4490-1123',
    examNumber: 'ENG-2026-0045',
    email: 'doyoon.jang@gmail.com',
    address: '광주광역시 북구 첨단과기로 123',
    recruitmentCategory: '토목/시설 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '해당없음',
    writtenScore: 68.0,
    interviewScore: 70.0,
    finalResult: '불합격',
    tags: ['과락주의'],
    memo: '필기시험 기준점수(70점) 미달로 과락 불합격.',
    sourceFileName: '기술직_접수명단.xlsx',
  },
  {
    id: 'sample_12',
    name: '한소희',
    phone: '010-2984-5561',
    examNumber: 'TECH-2026-0114',
    email: 'sohee.han@naver.com',
    address: '경기도 수원시 영통구 광교산로 154',
    recruitmentCategory: '전산/데이터 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 91.0,
    interviewScore: 89.0,
    finalResult: '최종 합격',
    tags: ['우수성적'],
    memo: '데이터베이스 전문 자격 가산점 반영 완료.',
    sourceFileName: '전산직렬_추가접수분.csv',
  },
  {
    id: 'sample_13',
    name: '오태양',
    phone: '010-8832-1904',
    examNumber: 'ENG-2026-0078',
    email: 'taeyang.oh@tech.co.kr',
    address: '울산광역시 남구 번영로 145',
    recruitmentCategory: '토목/시설 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급',
    writtenScore: 83.0,
    interviewScore: 84.5,
    finalResult: '심사 중',
    tags: ['2차면접대기'],
    memo: '면접 점수 종합 합산 및 신원조회 대기 중.',
    sourceFileName: '기술직_접수명단.xlsx',
  },
  {
    id: 'sample_14',
    name: '서예린',
    phone: '010-3309-4812',
    examNumber: 'ADM-2026-0240',
    email: 'yerin.seo@gmail.com',
    address: '강원특별자치도 춘천시 중앙로 1',
    recruitmentCategory: '일반행정 (지역: 강원)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '한부모가족',
    historyScore: '1급',
    writtenScore: 89.0,
    interviewScore: 91.0,
    finalResult: '최종 합격',
    tags: ['강원지역', '취약계층'],
    memo: '지역 구분 모집 최종 합격자.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_15',
    name: '신유찬',
    phone: '010-5190-3327',
    examNumber: 'PR-2026-0062',
    email: 'yuchan.shin@daum.net',
    address: '서울특별시 영등포구 여의대로 108',
    recruitmentCategory: '홍보/기획 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급',
    writtenScore: 88.5,
    interviewScore: 92.5,
    finalResult: '최종 합격',
    tags: ['홍보직우수'],
    memo: '홍보 포트폴리오 면접 우수자.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_16',
    name: '권나연',
    phone: '010-7741-6098',
    examNumber: 'PR-2026-0071',
    email: 'nayeon.kwon@design.kr',
    address: '충청남도 천안시 서북구 백석로 85',
    recruitmentCategory: '홍보/기획 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 84.0,
    interviewScore: 86.0,
    finalResult: '예비 합격',
    tags: ['예비1번'],
    memo: '홍보 기획직 예비 1순위.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_17',
    name: '황민석',
    phone: '010-6604-9281',
    examNumber: 'TECH-2026-0155',
    email: 'minseok.hwang@outlook.com',
    address: '경상북도 포항시 남구 포스코대로 281',
    recruitmentCategory: '전산/데이터 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '해당없음',
    writtenScore: 72.0,
    interviewScore: 68.0,
    finalResult: '불합격',
    tags: ['점수미달'],
    memo: '면접 평가 배수 밖 불합격 처리.',
    sourceFileName: '전산직렬_추가접수분.csv',
  },
  {
    id: 'sample_18',
    name: '안지민',
    phone: '010-9482-2031',
    examNumber: 'WEL-2026-0033',
    email: 'jimin.ahn@gmail.com',
    address: '전북특별자치도 전주시 완산구 효자로 225',
    recruitmentCategory: '사회복지 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급',
    writtenScore: 91.5,
    interviewScore: 90.0,
    finalResult: '최종 합격',
    tags: ['사회복지1급'],
    memo: '사회복지사 1급 소지자.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_19',
    name: '송준호',
    phone: '010-129-4829', // 자릿수 오류
    examNumber: 'ADM-2026-0299',
    email: 'junho.song@naver.com',
    address: '제주특별자치도 제주시 문연로 6',
    recruitmentCategory: '일반행정 (지역: 제주)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 82.0,
    interviewScore: 81.0,
    finalResult: '심사 중',
    tags: ['제주지역', '연락처확인'],
    memo: '연락처 중간번호 확인 필요.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_20',
    name: '배수빈',
    phone: '010-4092-7155',
    examNumber: 'ADM-2026-0305',
    email: 'subin.bae@gmail.com',
    address: '충청북도 청주시 상당구 상당로 82',
    recruitmentCategory: '일반행정 (전국)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 93.5,
    interviewScore: 95.0,
    finalResult: '최종 합격',
    tags: ['행정직수석'],
    memo: '일반행정 전체 최고점 합격.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
  {
    id: 'sample_21',
    name: '임도현',
    phone: '010-8310-5942',
    examNumber: 'ENG-2026-0099',
    email: 'dohyun.lim@kakao.com',
    address: '경상남도 창원시 의창구 중앙대로 300',
    recruitmentCategory: '토목/시설 (일반)',
    supportNeeds: '해당없음',
    disabilityStatus: '비대상',
    lowIncomeStatus: '비대상',
    historyScore: '2급',
    writtenScore: 88.0,
    interviewScore: 87.0,
    finalResult: '최종 합격',
    tags: ['토목기사'],
    memo: '토목기사 자격증 검증 완료.',
    sourceFileName: '기술직_접수명단.xlsx',
  },
  {
    id: 'sample_22',
    name: '노윤서',
    phone: '010-6789-1234',
    examNumber: 'ADM-2026-0318',
    email: 'yoonseo.roh@naver.com',
    address: '서울특별시 노원구 동일로 1405',
    recruitmentCategory: '일반행정 (전국)',
    supportNeeds: '시간연장 (1.2배)',
    disabilityStatus: '대상 (경증)',
    lowIncomeStatus: '비대상',
    historyScore: '1급',
    writtenScore: 89.0,
    interviewScore: 90.5,
    finalResult: '최종 합격',
    tags: ['장애인편의지원', '최종합격'],
    memo: '경증 편의지원 신청자. 시간연장 편의 제공 후 최종 합격.',
    sourceFileName: '2026_상반기_공채_접수대장.xlsx',
  },
];

export function generateSampleApplicants(): Applicant[] {
  const normalized = SAMPLE_RAW_APPLICANTS.map((raw) => buildNormalizedApplicant(raw));
  return recomputeApplicantsMetadata(normalized);
}

export function generateSampleParsedFiles(): ParsedFileSheet[] {
  const headers1 = [
    '성명',
    '연락처',
    '수험번호',
    '이메일',
    '거주주소',
    '채용분야',
    '편의지원신청',
    '장애여부',
    '저소득여부',
    '한국사능력',
    '필기시험점수',
    '면접시험점수',
    '최종결과',
    '비고사항',
  ];

  const rows1: Record<string, unknown>[] = [
    {
      성명: '  김민준 ',
      연락처: '+82 10-3948-1920',
      수험번호: 'ADM-2026-0101',
      이메일: 'MinJun.Kim@gmail.com',
      거주주소: '서울특별시 서초구 반포대로 58',
      채용분야: '일반행정 (전국)',
      편의지원신청: '해당없음',
      장애여부: '비대상',
      저소득여부: '비대상',
      한국사능력: '1급 (심화)',
      필기시험점수: 92.5,
      면접시험점수: 94.0,
      최종결과: '최종 합격',
      비고사항: '필기 및 면접 점수 최상위권',
    },
    {
      성명: '이서연',
      연락처: '010-8271-4409',
      수험번호: 'ADM-2026-0108',
      이메일: 'seoyeon.lee@kakao.com',
      거주주소: '경기도 성남시 분당구 판교역로 166',
      채용분야: '일반행정 (지역: 경기)',
      편의지원신청: '해당없음',
      장애여부: '비대상',
      저소득여부: '비대상',
      한국사능력: '2급 (기본)',
      필기시험점수: 89.5,
      면접시험점수: 92.0,
      최종결과: '최종 합격',
      비고사항: '지역 인재 추천 요건 충족',
    },
    {
      성명: '최수아',
      연락처: '010-5502-7731',
      수험번호: 'WEL-2026-0015',
      이메일: 'sua.choi@@gmail.com',
      거주주소: '대전광역시 유성구 대학로 99',
      채용분야: '사회복지 (일반)',
      편의지원신청: '확대문제지',
      장애여부: '비대상',
      저소득여부: '기초생활수급자',
      한국사능력: '3급',
      필기시험점수: 84.5,
      면접시험점수: 88.0,
      최종결과: '최종 합격',
      비고사항: '이메일 @ 오타 확인 필요',
    },
    {
      성명: '박지훈',
      연락처: '010-384-991',
      수험번호: 'TECH-2026-0088',
      이메일: 'jihun.park94@naver.com',
      거주주소: '인천광역시 부평구 부평대로 24',
      채용분야: '전산/데이터 (일반)',
      편의지원신청: '해당없음',
      장애여부: '대상 (경증)',
      저소득여부: '비대상',
      한국사능력: '1급',
      필기시험점수: 86.0,
      면접시험점수: 85.0,
      최종결과: '심사 중',
      비고사항: '연락처 끝자리 누락 확인 요망',
    },
  ];

  const headers2 = [
    '지원자명',
    '휴대전화',
    '응시번호',
    'E-mail',
    '주소지',
    '지원직렬',
    '편의제공',
    '장애구분',
    '취약계층',
    '한능검',
    '필기총점',
    '면접총점',
    '전형결과',
    '특이사항',
  ];

  const rows2: Record<string, unknown>[] = [
    {
      지원자명: '이 서 연',
      휴대전화: '1082714409',
      응시번호: 'ADM-2026-0108',
      'E-mail': 'seoyeon.lee@kakao.com',
      주소지: '경기도 성남시 분당구',
      지원직렬: '일반행정 (지역: 경기)',
      편의제공: '해당없음',
      장애구분: '비대상',
      취약계층: '비대상',
      한능검: '2급',
      필기총점: 89.5,
      면접총점: null,
      전형결과: '심사 중',
      특이사항: '중복 접수 대조 행',
    },
    {
      지원자명: '조성민',
      휴대전화: '010-7123-8840',
      응시번호: 'TECH-2026-0099',
      'E-mail': 'sungmin.cho@company.io',
      주소지: '서울특별시 마포구 월드컵북로 400',
      지원직렬: '전산/데이터 (일반)',
      편의제공: '별도시험실',
      장애구분: '대상 (중증)',
      취약계층: '차상위계층',
      한능검: '2급',
      필기총점: 90.0,
      면접총점: 93.0,
      전형결과: '최종 합격',
      특이사항: '중증장애인 편의제공 배정',
    },
  ];

  return [
    {
      id: `sheet_sample_1_${Date.now()}`,
      fileName: '2026_상반기_공개채용_원장.xlsx',
      sheetName: '응시자목록',
      headers: headers1,
      rows: rows1,
      mapping: autoRecommendColumnMapping(headers1),
    },
    {
      id: `sheet_sample_2_${Date.now() + 1}`,
      fileName: '기술직렬_추가원서접수대장.csv',
      sheetName: 'Sheet1',
      headers: headers2,
      rows: rows2,
      mapping: autoRecommendColumnMapping(headers2),
    },
  ];
}
