import { Applicant, ParsedFileSheet } from '../types/applicant';
import {
  buildNormalizedApplicant,
  RawApplicantInput,
  recomputeApplicantsMetadata,
} from './duplicateDetector';
import { autoRecommendColumnMapping } from './normalizers';

const SAMPLE_RAW_APPLICANTS: RawApplicantInput[] = [
  {
    id: 'sample_01',
    name: '  김민준 ',
    phone: '+82 10-3948-1920',
    email: 'MinJun.Kim@gmail.com ',
    position: '프론트엔드 엔지니어',
    source: '원티드',
    experience: '4년 6개월',
    appliedDate: '2026.09.18',
    status: '서류 통과',
    tags: ['React', '디자인시스템', '우선검토'],
    memo: '대규모 B2B SaaS 대시보드 구축 경험 보유. 포트폴리오 완성도 우수.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_02',
    name: '김민준',
    phone: '01039481920',
    email: 'minjun.kim@gmail.com',
    position: '풀스택 개발자',
    source: '자사 채용사이트',
    experience: '4.5',
    appliedDate: '2026-09-21',
    status: '검토 전',
    tags: ['React', 'Node.js'],
    memo: '프론트엔드 공고 지원 후 풀스택 포지션에도 추가 지원함.',
    sourceFileName: '자사홈페이지_접수분.csv',
  },
  {
    id: 'sample_03',
    name: '이서연',
    phone: '010-8271-4409',
    email: 'seoyeon.lee@kakao.com',
    position: '프로덕트 디자이너',
    source: '원티드',
    experience: '3년',
    appliedDate: '2026/09/14',
    status: '서류 통과',
    tags: ['Figma', 'UX리서치'],
    memo: '핀테크 앱 리브랜딩 리드 경험. 과제 전형 안내 예정.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_04',
    name: '이 서 연',
    phone: '1082714409',
    email: 'seoyeon.lee@kakao.com',
    position: '프로덕트 디자이너',
    source: '사람인',
    experience: '3',
    appliedDate: '2026.09.19',
    status: '검토 전',
    tags: ['포트폴리오첨부'],
    memo: '사람인을 통해 동일 포지션에 중복 접수된 내역 (이력서 버전 2.1).',
    sourceFileName: '사람인_공채접수내역.xlsx',
  },
  {
    id: 'sample_05',
    name: '박지훈',
    phone: '010-384-991',
    email: 'jihun.park94@naver.com',
    position: '백엔드 엔지니어',
    source: '사람인',
    experience: '5년',
    appliedDate: '2026-09-15',
    status: '보류',
    tags: ['Spring', 'Kotlin'],
    memo: '이력서 상 연락처 끝자리 누락. 이메일로 연락처 재확인 요청 필요.',
    sourceFileName: '사람인_공채접수내역.xlsx',
  },
  {
    id: 'sample_06',
    name: '최수아',
    phone: '010-5502-7731',
    email: 'sua.choi@@gmail.com',
    position: '데이터 애널리스트',
    source: '리멤버',
    experience: '2년 6개월',
    appliedDate: '2026년 9월 17일',
    status: '검토 전',
    tags: ['SQL', 'Tableau'],
    memo: '커머스 코호트 분석 및 퍼널 개선 프로젝트 경험.',
    sourceFileName: '리멤버_스카우트_지원자.xlsx',
  },
  {
    id: 'sample_07',
    name: '정현우',
    phone: '010-9012-6634',
    email: 'hyunwoo.jung@devmail.kr',
    position: '백엔드 엔지니어',
    source: '원티드',
    experience: '6년',
    appliedDate: '2026-09-12',
    status: '서류 통과',
    tags: ['대용량트래픽', 'MSA', '핵심인재'],
    memo: '결제 정산 파이프라인 설계 리드. 1차 기술면접 일정 조율 중.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_08',
    name: '정현우',
    phone: '+82-10-9012-6634',
    email: 'hyunwoo.jung@devmail.kr',
    position: '데이터 엔지니어',
    source: '링크드인',
    experience: '6년차',
    appliedDate: '2026.09.20',
    status: '검토 전',
    tags: ['Kafka', 'Spark'],
    memo: '백엔드 포지션과 데이터 엔지니어 포지션 복수 지원. 면접 시 희망 직무 확인.',
    sourceFileName: '링크드인_다이렉트.csv',
  },
  {
    id: 'sample_09',
    name: '강하은',
    phone: '010-2219',
    email: 'haeun.kang@naver',
    position: '마케팅 매니저',
    source: '잡코리아',
    experience: '신입',
    appliedDate: '20260922',
    status: '검토 전',
    tags: ['콘텐츠마케팅'],
    memo: '파일 변환 중 연락처 및 이메일 도메인 일부 잘림. 원본 PDF 이력서 대조 필요.',
    sourceFileName: '잡코리아_수시채용.xlsx',
  },
  {
    id: 'sample_10',
    name: '조성민',
    phone: '010-7123-8840',
    email: 'sungmin.cho@company.io',
    position: '프론트엔드 엔지니어',
    source: '사내 추천',
    experience: '3.5년',
    appliedDate: '2026-09-10',
    status: '서류 통과',
    tags: ['사내추천', 'TypeScript', '성능최적화'],
    memo: '플랫폼팀 김수현 님 추천. 웹팩/번들 최적화 경험 풍부.',
    sourceFileName: '사내추천_접수대장.xlsx',
  },
  {
    id: 'sample_11',
    name: '윤지아',
    phone: '010-6341-0982',
    email: 'jia.yoon@studio.kr',
    position: '프로덕트 매니저 (PO)',
    source: '원티드',
    experience: '7년',
    appliedDate: '2026-09-16',
    status: '서류 통과',
    tags: ['B2B', '로드맵설계', '시니어'],
    memo: 'HR SaaS 도메인 경력 4년 포함. 도메인 이해도 매우 높음.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_12',
    name: '장도윤',
    phone: '010-4490-1123',
    email: 'doyoon.jang@gmail.com',
    position: '백엔드 엔지니어',
    source: '사람인',
    experience: '1년 6개월',
    appliedDate: '2026-09-19',
    status: '탈락',
    tags: ['주니어', 'Node.js'],
    memo: '현재 채용 중인 시니어 백엔드 자격 요건(4년 이상)과 연차 차이로 아쉽게 불합격.',
    sourceFileName: '사람인_공채접수내역.xlsx',
  },
  {
    id: 'sample_13',
    name: '한소희',
    phone: '010-2984-5561',
    email: 'sohee.han@naver.com',
    position: '데이터 애널리스트',
    source: '원티드',
    experience: '3년',
    appliedDate: '2026-09-21',
    status: '검토 전',
    tags: ['Python', 'A/B테스트'],
    memo: '실험 플랫폼 설계 및 지표 정의 경험 보유.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_14',
    name: '오태양',
    phone: '010-8832-1904',
    email: 'taeyang.oh@tech.co.kr',
    position: '데브옵스 엔지니어',
    source: '리멤버',
    experience: '8년',
    appliedDate: '2026-09-13',
    status: '보류',
    tags: ['Kubernetes', 'AWS', 'Terraform'],
    memo: '기술 역량 우수하나 희망 연봉 밴드 상단 초과로 디렉터 검토 대기.',
    sourceFileName: '리멤버_스카우트_지원자.xlsx',
  },
  {
    id: 'sample_15',
    name: '서예린',
    phone: '010-3309-4812',
    email: 'yerin.seo@gmail.com',
    position: '프론트엔드 엔지니어',
    source: '자사 채용사이트',
    experience: '신입',
    appliedDate: '2026-09-24',
    status: '검토 전',
    tags: ['신입', '오픈소스기여'],
    memo: '컴퓨터공학 졸업 예정. 오픈소스 UI 라이브러리 컨트리뷰션 이력 인상적.',
    sourceFileName: '자사홈페이지_접수분.csv',
  },
  {
    id: 'sample_16',
    name: '신유찬',
    phone: '010-5190-3327',
    email: 'yuchan.shin@daum.net',
    position: '마케팅 매니저',
    source: '잡코리아',
    experience: '4년',
    appliedDate: '2026-09-18',
    status: '서류 통과',
    tags: ['퍼포먼스마케팅', 'GA4', 'CRM'],
    memo: 'B2B 리드 제너레이션 캠페인 ROAS 240% 달성 사례 수록.',
    sourceFileName: '잡코리아_수시채용.xlsx',
  },
  {
    id: 'sample_17',
    name: '권나연',
    phone: '010-7741-6098',
    email: 'nayeon.kwon@design.kr',
    position: '프로덕트 디자이너',
    source: '원티드',
    experience: '5년',
    appliedDate: '2026-09-15',
    status: '보류',
    tags: ['디자인시스템', 'B2C'],
    memo: '시각 완성도 높음. 복합 테이블 UI 설계 경험은 면접에서 추가 확인 필요.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
  {
    id: 'sample_18',
    name: '황민석',
    phone: '010-6604-9281',
    email: 'minseok.hwang@outlook.com',
    position: '백엔드 엔지니어',
    source: '링크드인',
    experience: '9년',
    appliedDate: '2026-09-11',
    status: '탈락',
    tags: ['테크리드', 'Go'],
    memo: '타사 오퍼 수락으로 전형 중도 기권 연락 받음.',
    sourceFileName: '링크드인_다이렉트.csv',
  },
  {
    id: 'sample_19',
    name: '안지민',
    phone: '010-9482-2031',
    email: 'jimin.ahn@gmail.com',
    position: '프로덕트 매니저 (PO)',
    source: '사내 추천',
    experience: '4년',
    appliedDate: '2026-09-23',
    status: '검토 전',
    tags: ['사내추천', '그로스'],
    memo: '전 직장 동료 추천. 온보딩 전환율 개선 프로젝트 리드.',
    sourceFileName: '사내추천_접수대장.xlsx',
  },
  {
    id: 'sample_20',
    name: '송준호',
    phone: '010-129-4829',
    email: 'junho.song@naver.com',
    position: '풀스택 개발자',
    source: '사람인',
    experience: '2년',
    appliedDate: '2026-09-25',
    status: '검토 전',
    tags: ['Next.js', 'NestJS'],
    memo: '연락처 중간 번호 3자리 오기재 의심. 이메일로 먼저 연락 요망.',
    sourceFileName: '사람인_공채접수내역.xlsx',
  },
  {
    id: 'sample_21',
    name: '배수빈',
    phone: '010-4092-7155',
    email: 'subin.bae@gmail.com',
    position: 'HR 매니저 (채용)',
    source: '자사 채용사이트',
    experience: '3년',
    appliedDate: '2026-09-26',
    status: '서류 통과',
    tags: ['IT채용', '다이렉트소싱'],
    memo: '테크 직군 다이렉트 소싱 및 ATS 도입 프로젝트 유경험자.',
    sourceFileName: '자사홈페이지_접수분.csv',
  },
  {
    id: 'sample_22',
    name: '임도현',
    phone: '010-8310-5942',
    email: 'dohyun.lim@kakao.com',
    position: '데브옵스 엔지니어',
    source: '원티드',
    experience: '18개월',
    appliedDate: '2026-09-27',
    status: '검토 전',
    tags: ['CI/CD', 'Docker'],
    memo: '클라우드 인프라 자동화 파이프라인 구축 경험.',
    sourceFileName: '원티드_지원자목록_9월.xlsx',
  },
];

export function generateSampleApplicants(): Applicant[] {
  const normalized = SAMPLE_RAW_APPLICANTS.map((raw) => buildNormalizedApplicant(raw));
  return recomputeApplicantsMetadata(normalized);
}

export function generateSampleParsedFiles(): ParsedFileSheet[] {
  const headers1 = [
    '지원자 성명',
    '휴대폰 번호',
    'E-mail 주소',
    '지원직무',
    '유입채널',
    '총 경력기간',
    '접수일자',
    '특이사항(비고)',
    '이력서 열람여부',
  ];

  const rows1: Record<string, unknown>[] = [
    {
      '지원자 성명': '  김민준 ',
      '휴대폰 번호': '+82 10-3948-1920',
      'E-mail 주소': 'MinJun.Kim@gmail.com',
      지원직무: '프론트엔드 엔지니어',
      유입채널: '원티드',
      '총 경력기간': '4년 6개월',
      접수일자: '2026.09.18',
      '특이사항(비고)': '대규모 B2B SaaS 대시보드 구축 경험',
      '이력서 열람여부': '열람완료',
    },
    {
      '지원자 성명': '이서연',
      '휴대폰 번호': '010-8271-4409',
      'E-mail 주소': 'seoyeon.lee@kakao.com',
      지원직무: '프로덕트 디자이너',
      유입채널: '원티드',
      '총 경력기간': '3년',
      접수일자: '2026/09/14',
      '특이사항(비고)': '핀테크 앱 리브랜딩 리드 경험',
      '이력서 열람여부': '열람완료',
    },
    {
      '지원자 성명': '노윤서',
      '휴대폰 번호': '01067891234',
      'E-mail 주소': 'YoonSeo.Roh@naver.com ',
      지원직무: '프론트엔드 엔지니어',
      유입채널: '원티드',
      '총 경력기간': '2년 6개월',
      접수일자: '2026.09.28',
      '특이사항(비고)': '웹 접근성 및 디자인 시스템 컴포넌트 개발',
      '이력서 열람여부': '미열람',
    },
    {
      '지원자 성명': '문지후',
      '휴대폰 번호': '010-445-882',
      'E-mail 주소': 'jihoo.moon@gmail.com',
      지원직무: '백엔드 엔지니어',
      유입채널: '원티드',
      '총 경력기간': '신입',
      접수일자: '2026-09-29',
      '특이사항(비고)': '연락처 오타 확인 필요',
      '이력서 열람여부': '미열람',
    },
  ];

  const headers2 = [
    'Name',
    'Mobile',
    'Email',
    'Position',
    'Source',
    'Career',
    'Applied Date',
    'Memo',
  ];

  const rows2: Record<string, unknown>[] = [
    {
      Name: '이 서 연',
      Mobile: '1082714409',
      Email: 'seoyeon.lee@kakao.com',
      Position: '프로덕트 디자이너',
      Source: '사람인',
      Career: '3년',
      'Applied Date': '2026-09-19',
      Memo: '사람인 중복 접수분 (포트폴리오 링크 추가됨)',
    },
    {
      Name: '김민준',
      Mobile: '010-3948-1920',
      Email: 'minjun.kim@gmail.com',
      Position: '풀스택 개발자',
      Source: '자사 채용사이트',
      Career: '4.5',
      'Applied Date': '2026.09.21',
      Memo: '복수 포지션 지원 사례 (프론트엔드 + 풀스택)',
    },
    {
      Name: '하준영',
      Mobile: '+82 10 5544 3322',
      Email: 'junyoung.ha@@company.com',
      Position: '데이터 애널리스트',
      Source: '리멤버',
      Career: '5년',
      'Applied Date': '20260930',
      Memo: '이메일 주소 @ 중복 입력됨',
    },
  ];

  return [
    {
      id: `sheet_sample_1_${Date.now()}`,
      fileName: '원티드_수시채용_지원자명단.xlsx',
      sheetName: '지원자목록',
      headers: headers1,
      rows: rows1,
      mapping: autoRecommendColumnMapping(headers1),
    },
    {
      id: `sheet_sample_2_${Date.now() + 1}`,
      fileName: '사람인_자사채용_통합접수.csv',
      sheetName: 'Sheet1',
      headers: headers2,
      rows: rows2,
      mapping: autoRecommendColumnMapping(headers2),
    },
  ];
}
